package com.versawork.http.constant;

public enum CacheConstants {

	FACILITY_NOTICE("FNO"), FACILITY_PROVIDER("FPR"), FACILITY_SERVICE("FSE"),

	PATIENT_LAB("PLAB"), PATIENT_MEDICATION("PMED"), PATIENT_IMAGING("PIMG"),

	PATIENT_ALLERGY("PALL"), PATIENT_PROBLEM("PPROB"), PATIENT_VISIT("PVIS"), PATIENT_FEEDBACK("PFED"), PATIENT_CARE_PLAN(
			"PCPL"), PATIENT_CARE_TEAM("PCTE"), PATIENT_DIAGNOSIS("PDIA"), PATIENT_FUNCTIONAL_STATUS("PFST"), PATIENT_IMMUNIZATION(
			"PIMM"), PATIENT_PROCEDURE("PPROC"), PATIENT_VISIT_INPATIENT("PVIN"), PATIENT_VITAL_SIGN("PVSI"),

	PATIENT_VERIFICATION("PVT"), PATIENT_LABHISTORY("PLHIS"),

	// NOT CACHED SINCE IT IS UPDATED BY SCHEDULER EVERY FEW MINUTES
	PATIENT_UPCOMINNG_APPOINTMENT("PUA");

	private String code;

	private CacheConstants(String code) {
		this.code = code;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
