//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element ref="{urn:hl7-org:v3}id"/>
 *           &lt;element ref="{urn:hl7-org:v3}code"/>
 *           &lt;element ref="{urn:hl7-org:v3}text"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{urn:hl7-org:v3}templateId"/>
 *           &lt;choice>
 *             &lt;sequence>
 *               &lt;element ref="{urn:hl7-org:v3}id"/>
 *               &lt;element ref="{urn:hl7-org:v3}code"/>
 *               &lt;element ref="{urn:hl7-org:v3}statusCode"/>
 *               &lt;choice minOccurs="0">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:hl7-org:v3}performer"/>
 *                   &lt;element ref="{urn:hl7-org:v3}participant" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;element ref="{urn:hl7-org:v3}effectiveTime"/>
 *               &lt;/choice>
 *               &lt;element ref="{urn:hl7-org:v3}entryRelationship"/>
 *             &lt;/sequence>
 *             &lt;sequence>
 *               &lt;element ref="{urn:hl7-org:v3}code"/>
 *               &lt;element ref="{urn:hl7-org:v3}text"/>
 *               &lt;element ref="{urn:hl7-org:v3}statusCode"/>
 *             &lt;/sequence>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/choice>
 *       &lt;attribute name="moodCode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="DEF"/>
 *             &lt;enumeration value="EVN"/>
 *             &lt;enumeration value="INT"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="classCode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ACT"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "templateId", "id", "code", "statusCode", "effectiveTime", "entryRelationship",
		"content" })
@XmlRootElement(name = "act")
public class Act {

	@XmlElement(required = true)
	protected TemplateId templateId;
	@XmlElement(required = true)
	protected Id id;
	@XmlElement(required = true)
	protected Code code;
	@XmlElement(required = true)
	protected EntryRelationship entryRelationship;
	@XmlElement(required = true)
	protected EffectiveTime effectiveTime;
	@XmlElement(required = true)
	protected StatusCode statusCode;
	@XmlElement
	protected List<Object> content;
	@XmlAttribute(name = "moodCode", required = true)
	protected String moodCode;
	@XmlAttribute(name = "classCode", required = true)
	protected String classCode;

	public EffectiveTime getEffectiveTime() {
		return effectiveTime;
	}

	public void setEffectiveTime(EffectiveTime effectiveTime) {
		this.effectiveTime = effectiveTime;
	}

	public StatusCode getStatusCode() {
		return statusCode;
	}

	public void setStatusCode(StatusCode statusCode) {
		this.statusCode = statusCode;
	}

	/**
	 * Gets the rest of the content model.
	 * 
	 * <p>
	 * You are getting this "catch-all" property because of the following
	 * reason: The field name "Id" is used by two different parts of a schema.
	 * See: line 183 of
	 * file:/C:/Users/Nitin/Workspace/Versaworks_Phase4/JAXB/phase2_xmlSchema
	 * .xsd line 175 of
	 * file:/C:/Users/Nitin/Workspace/Versaworks_Phase4/JAXB/phase2_xmlSchema
	 * .xsd
	 * <p>
	 * To get rid of this property, apply a property customization to one of
	 * both of the following declarations to change their names: Gets the value
	 * of the content property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the content property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getContent().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Id }
	 * {@link JAXBElement }{@code <}{@link TEffectiveTime }{@code >}
	 * {@link StatusCode } {@link Participant } {@link EntryRelationship }
	 * {@link TemplateId } {@link Text } {@link Performer } {@link Code }
	 * 
	 * 
	 */
	public List<Object> getContent() {
		if (content == null) {
			content = new ArrayList<Object>();
		}
		return this.content;
	}

	/**
	 * Gets the value of the moodCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMoodCode() {
		return moodCode;
	}

	/**
	 * Sets the value of the moodCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMoodCode(String value) {
		this.moodCode = value;
	}

	/**
	 * Gets the value of the classCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClassCode() {
		return classCode;
	}

	/**
	 * Sets the value of the classCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setClassCode(String value) {
		this.classCode = value;
	}

	public TemplateId getTemplateId() {
		return templateId;
	}

	public void setTemplateId(TemplateId templateId) {
		this.templateId = templateId;
	}

	public Id getId() {
		return id;
	}

	public void setId(Id id) {
		this.id = id;
	}

	public Code getCode() {
		return code;
	}

	public void setCode(Code code) {
		this.code = code;
	}

	public EntryRelationship getEntryRelationship() {
		return entryRelationship;
	}

	public void setEntryRelationship(EntryRelationship entryRelationship) {
		this.entryRelationship = entryRelationship;
	}

}
