//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{urn:hl7-org:v3}streetAddressLine" maxOccurs="unbounded"/>
 *         &lt;element ref="{urn:hl7-org:v3}city"/>
 *         &lt;element ref="{urn:hl7-org:v3}state"/>
 *         &lt;element ref="{urn:hl7-org:v3}postalCode"/>
 *       &lt;/sequence>
 *       &lt;attribute name="use">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="HP"/>
 *             &lt;enumeration value="WP"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="nullFlavor">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="NI"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "streetAddressLine", "city", "state", "postalCode", "country" })
@XmlRootElement(name = "addr")
public class Addr {

	protected List<String> streetAddressLine;
	protected String city;
	protected String state;
	protected Long postalCode;
	@XmlElement(required = true)
	protected String country;
	@XmlAttribute(name = "use")
	protected String use;
	@XmlAttribute(name = "nullFlavor")
	protected String nullFlavor;

	/**
	 * Gets the value of the streetAddressLine property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the streetAddressLine property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getStreetAddressLine().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getStreetAddressLine() {
		if (streetAddressLine == null) {
			streetAddressLine = new ArrayList<String>();
		}
		return this.streetAddressLine;
	}

	/**
	 * Gets the value of the city property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCity() {
		return city;
	}

	/**
	 * Sets the value of the city property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCity(String value) {
		this.city = value;
	}

	/**
	 * Gets the value of the state property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getState() {
		return state;
	}

	/**
	 * Sets the value of the state property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setState(String value) {
		this.state = value;
	}

	/**
	 * Gets the value of the postalCode property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Long getPostalCode() {
		return postalCode;
	}

	/**
	 * Sets the value of the postalCode property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setPostalCode(Long value) {
		this.postalCode = value;
	}

	/**
	 * Gets the value of the use property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	/**
	 * Gets the value of the country property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * Sets the value of the country property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCountry(String value) {
		this.country = value;
	}

	public String getUse() {
		return use;
	}

	/**
	 * Sets the value of the use property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUse(String value) {
		this.use = value;
	}

	/**
	 * Gets the value of the nullFlavor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNullFlavor() {
		return nullFlavor;
	}

	/**
	 * Sets the value of the nullFlavor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNullFlavor(String value) {
		this.nullFlavor = value;
	}

}