//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}manufacturerModelName"/>
 *         &lt;element ref="{urn:hl7-org:v3}softwareName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "manufacturerModelName", "softwareName" })
@XmlRootElement(name = "assignedAuthoringDevice")
public class AssignedAuthoringDevice {

	@XmlElement(required = true)
	protected String manufacturerModelName;
	@XmlElement(required = true)
	protected String softwareName;

	/**
	 * Gets the value of the manufacturerModelName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getManufacturerModelName() {
		return manufacturerModelName;
	}

	/**
	 * Sets the value of the manufacturerModelName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setManufacturerModelName(String value) {
		this.manufacturerModelName = value;
	}

	/**
	 * Gets the value of the softwareName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSoftwareName() {
		return softwareName;
	}

	/**
	 * Sets the value of the softwareName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSoftwareName(String value) {
		this.softwareName = value;
	}

}
