//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}realmCode"/>
 *         &lt;element ref="{urn:hl7-org:v3}typeId"/>
 *         &lt;element ref="{urn:hl7-org:v3}templateId"/>
 *         &lt;element ref="{urn:hl7-org:v3}id"/>
 *         &lt;element ref="{urn:hl7-org:v3}code"/>
 *         &lt;element ref="{urn:hl7-org:v3}title"/>
 *         &lt;element ref="{urn:hl7-org:v3}effectiveTime"/>
 *         &lt;element ref="{urn:hl7-org:v3}confidentialityCode"/>
 *         &lt;element ref="{urn:hl7-org:v3}languageCode"/>
 *         &lt;element ref="{urn:hl7-org:v3}recordTarget"/>
 *         &lt;element ref="{urn:hl7-org:v3}author"/>
 *         &lt;element ref="{urn:hl7-org:v3}custodian"/>
 *         &lt;element ref="{urn:hl7-org:v3}participant" maxOccurs="unbounded"/>
 *         &lt;element ref="{urn:hl7-org:v3}documentationOf"/>
 *         &lt;element ref="{urn:hl7-org:v3}component"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "realmCode", "typeId", "templateId", "id", "code", "title", "effectiveTime",
		"confidentialityCode", "languageCode", "recordTarget", "author", "custodian", "participant",
		"legalAuthenticator", "documentationOf", "component" })
@XmlRootElement(name = "ClinicalDocument")
public class ClinicalDocument {

	@XmlElement(required = true)
	protected RealmCode realmCode;
	@XmlElement(required = true)
	protected TypeId typeId;
	@XmlElement(required = true)
	protected TemplateId templateId;
	@XmlElement(required = true)
	protected Id id;
	@XmlElement(required = true)
	protected Code code;
	@XmlElement(required = true)
	protected String title;
	@XmlElement(required = true)
	protected TEffectiveTime effectiveTime;
	@XmlElement(required = true)
	protected ConfidentialityCode confidentialityCode;
	@XmlElement(required = true)
	protected LanguageCode languageCode;
	@XmlElement(required = true)
	protected RecordTarget recordTarget;
	@XmlElement(required = true)
	protected Author author;
	@XmlElement(required = true)
	protected Custodian custodian;
	@XmlElement(required = true)
	protected List<Participant> participant;
	@XmlElement(required = true)
	protected LegalAuthenticator legalAuthenticator;
	@XmlElement(required = true)
	protected DocumentationOf documentationOf;
	@XmlElement(required = true)
	protected Component component;

	@XmlAttribute(name = "xmlns")
	protected String xmlns;

	@XmlAttribute(name = "xmlns:xsi")
	protected String xmlnsXsi;

	@XmlAttribute(name = "xmlns:voc")
	protected String xmlnsVoc;

	@XmlAttribute(name = "xmlns:sdtc")
	protected String xmlnsSdtc;

	public String getXmlns() {
		return xmlns;
	}

	public String getXmlnsXsi() {
		return xmlnsXsi;
	}

	public void setXmlnsXsi(String xmlnsXsi) {
		this.xmlnsXsi = xmlnsXsi;
	}

	public String getXmlnsVoc() {
		return xmlnsVoc;
	}

	public void setXmlnsVoc(String xmlnsVoc) {
		this.xmlnsVoc = xmlnsVoc;
	}

	public String getXmlnsSdtc() {
		return xmlnsSdtc;
	}

	public void setXmlnsSdtc(String xmlnsSdtc) {
		this.xmlnsSdtc = xmlnsSdtc;
	}

	public void setParticipant(List<Participant> participant) {
		this.participant = participant;
	}

	public void setXmlns(String xmlns) {
		this.xmlns = xmlns;
	}

	public LegalAuthenticator getLegalAuthenticator() {
		return legalAuthenticator;
	}

	public void setLegalAuthenticator(LegalAuthenticator legalAuthenticator) {
		this.legalAuthenticator = legalAuthenticator;
	}

	/**
	 * Gets the value of the realmCode property.
	 * 
	 * @return possible object is {@link RealmCode }
	 * 
	 */
	public RealmCode getRealmCode() {
		return realmCode;
	}

	/**
	 * Sets the value of the realmCode property.
	 * 
	 * @param value
	 *            allowed object is {@link RealmCode }
	 * 
	 */
	public void setRealmCode(RealmCode value) {
		this.realmCode = value;
	}

	/**
	 * Gets the value of the typeId property.
	 * 
	 * @return possible object is {@link TypeId }
	 * 
	 */
	public TypeId getTypeId() {
		return typeId;
	}

	/**
	 * Sets the value of the typeId property.
	 * 
	 * @param value
	 *            allowed object is {@link TypeId }
	 * 
	 */
	public void setTypeId(TypeId value) {
		this.typeId = value;
	}

	/**
	 * Gets the value of the templateId property.
	 * 
	 * @return possible object is {@link TemplateId }
	 * 
	 */
	public TemplateId getTemplateId() {
		return templateId;
	}

	/**
	 * Sets the value of the templateId property.
	 * 
	 * @param value
	 *            allowed object is {@link TemplateId }
	 * 
	 */
	public void setTemplateId(TemplateId value) {
		this.templateId = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link Id }
	 * 
	 */
	public Id getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link Id }
	 * 
	 */
	public void setId(Id value) {
		this.id = value;
	}

	/**
	 * Gets the value of the code property.
	 * 
	 * @return possible object is {@link Code }
	 * 
	 */
	public Code getCode() {
		return code;
	}

	/**
	 * Sets the value of the code property.
	 * 
	 * @param value
	 *            allowed object is {@link Code }
	 * 
	 */
	public void setCode(Code value) {
		this.code = value;
	}

	/**
	 * Gets the value of the title property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTitle(String value) {
		this.title = value;
	}

	/**
	 * Gets the value of the effectiveTime property.
	 * 
	 * @return possible object is {@link TEffectiveTime }
	 * 
	 */
	public TEffectiveTime getEffectiveTime() {
		return effectiveTime;
	}

	/**
	 * Sets the value of the effectiveTime property.
	 * 
	 * @param value
	 *            allowed object is {@link TEffectiveTime }
	 * 
	 */
	public void setEffectiveTime(TEffectiveTime value) {
		this.effectiveTime = value;
	}

	/**
	 * Gets the value of the confidentialityCode property.
	 * 
	 * @return possible object is {@link ConfidentialityCode }
	 * 
	 */
	public ConfidentialityCode getConfidentialityCode() {
		return confidentialityCode;
	}

	/**
	 * Sets the value of the confidentialityCode property.
	 * 
	 * @param value
	 *            allowed object is {@link ConfidentialityCode }
	 * 
	 */
	public void setConfidentialityCode(ConfidentialityCode value) {
		this.confidentialityCode = value;
	}

	/**
	 * Gets the value of the languageCode property.
	 * 
	 * @return possible object is {@link LanguageCode }
	 * 
	 */
	public LanguageCode getLanguageCode() {
		return languageCode;
	}

	/**
	 * Sets the value of the languageCode property.
	 * 
	 * @param value
	 *            allowed object is {@link LanguageCode }
	 * 
	 */
	public void setLanguageCode(LanguageCode value) {
		this.languageCode = value;
	}

	/**
	 * Gets the value of the recordTarget property.
	 * 
	 * @return possible object is {@link RecordTarget }
	 * 
	 */
	public RecordTarget getRecordTarget() {
		return recordTarget;
	}

	/**
	 * Sets the value of the recordTarget property.
	 * 
	 * @param value
	 *            allowed object is {@link RecordTarget }
	 * 
	 */
	public void setRecordTarget(RecordTarget value) {
		this.recordTarget = value;
	}

	/**
	 * Gets the value of the author property.
	 * 
	 * @return possible object is {@link Author }
	 * 
	 */
	public Author getAuthor() {
		return author;
	}

	/**
	 * Sets the value of the author property.
	 * 
	 * @param value
	 *            allowed object is {@link Author }
	 * 
	 */
	public void setAuthor(Author value) {
		this.author = value;
	}

	/**
	 * Gets the value of the custodian property.
	 * 
	 * @return possible object is {@link Custodian }
	 * 
	 */
	public Custodian getCustodian() {
		return custodian;
	}

	/**
	 * Sets the value of the custodian property.
	 * 
	 * @param value
	 *            allowed object is {@link Custodian }
	 * 
	 */
	public void setCustodian(Custodian value) {
		this.custodian = value;
	}

	/**
	 * Gets the value of the participant property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the participant property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getParticipant().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Participant }
	 * 
	 * 
	 */
	public List<Participant> getParticipant() {
		if (participant == null) {
			participant = new ArrayList<Participant>();
		}
		return this.participant;
	}

	/**
	 * Gets the value of the documentationOf property.
	 * 
	 * @return possible object is {@link DocumentationOf }
	 * 
	 */
	public DocumentationOf getDocumentationOf() {
		return documentationOf;
	}

	/**
	 * Sets the value of the documentationOf property.
	 * 
	 * @param value
	 *            allowed object is {@link DocumentationOf }
	 * 
	 */
	public void setDocumentationOf(DocumentationOf value) {
		this.documentationOf = value;
	}

	/**
	 * Gets the value of the component property.
	 * 
	 * @return possible object is {@link Component }
	 * 
	 */
	public Component getComponent() {
		return component;
	}

	/**
	 * Sets the value of the component property.
	 * 
	 * @param value
	 *            allowed object is {@link Component }
	 * 
	 */
	public void setComponent(Component value) {
		this.component = value;
	}

}
