//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}originalText" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="code">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="10160-0"/>
 *             &lt;enumeration value="11369-6"/>
 *             &lt;enumeration value="11450-4"/>
 *             &lt;enumeration value="18776-5"/>
 *             &lt;enumeration value="25436-6"/>
 *             &lt;enumeration value="29762-2"/>
 *             &lt;enumeration value="30954-2"/>
 *             &lt;enumeration value="310965"/>
 *             &lt;enumeration value="313782"/>
 *             &lt;enumeration value="33999-4"/>
 *             &lt;enumeration value="34133-9"/>
 *             &lt;enumeration value="399208008"/>
 *             &lt;enumeration value="405279007"/>
 *             &lt;enumeration value="46240-8"/>
 *             &lt;enumeration value="47420-5"/>
 *             &lt;enumeration value="47519-4"/>
 *             &lt;enumeration value="48765-2"/>
 *             &lt;enumeration value="48768-6"/>
 *             &lt;enumeration value="55607006"/>
 *             &lt;enumeration value="8653-8"/>
 *             &lt;enumeration value="8716-3"/>
 *             &lt;enumeration value="ASSERTION"/>
 *             &lt;enumeration value="CONC"/>
 *             &lt;enumeration value="IMMUNIZ"/>
 *             &lt;enumeration value="PAYOR"/>
 *             &lt;enumeration value="PINSTRUCT"/>
 *             &lt;enumeration value="SELF"/>
 *             &lt;enumeration value="SEV"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="codeSystem">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="1.3.6.1.4.1.19376.1.5.3.2"/>
 *             &lt;enumeration value="2.16.840.1.113883.5.110"/>
 *             &lt;enumeration value="2.16.840.1.113883.5.111"/>
 *             &lt;enumeration value="2.16.840.1.113883.5.4"/>
 *             &lt;enumeration value="2.16.840.1.113883.5.6"/>
 *             &lt;enumeration value="2.16.840.1.113883.6.1"/>
 *             &lt;enumeration value="2.16.840.1.113883.6.88"/>
 *             &lt;enumeration value="2.16.840.1.113883.6.96"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="nullFlavor">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="NA"/>
 *             &lt;enumeration value="NI"/>
 *             &lt;enumeration value="UNK"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="displayName">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Acetaminophen 325 MG Oral Tablet"/>
 *             &lt;enumeration value="Allergies, adverse reactions, alerts"/>
 *             &lt;enumeration value="Alleriges, adverse reactions, alerts"/>
 *             &lt;enumeration value="Attending Physician"/>
 *             &lt;enumeration value="Concern"/>
 *             &lt;enumeration value="Functional Status"/>
 *             &lt;enumeration value="History of encounters"/>
 *             &lt;enumeration value="History of immunizations"/>
 *             &lt;enumeration value="History of medication use"/>
 *             &lt;enumeration value="History of procedures"/>
 *             &lt;enumeration value="Hospital Discharge Instructions"/>
 *             &lt;enumeration value="Ibuprofen 200 MG Oral Tablet"/>
 *             &lt;enumeration value="Laboratory Results"/>
 *             &lt;enumeration value="Payment sources"/>
 *             &lt;enumeration value="Plan of Care"/>
 *             &lt;enumeration value="Problem"/>
 *             &lt;enumeration value="Problem list"/>
 *             &lt;enumeration value="Relevant diagnostic tests"/>
 *             &lt;enumeration value="Self"/>
 *             &lt;enumeration value="Severity"/>
 *             &lt;enumeration value="Social history"/>
 *             &lt;enumeration value="Status"/>
 *             &lt;enumeration value="Summarization of Episode Note"/>
 *             &lt;enumeration value="Vital signs"/>
 *             &lt;enumeration value="X-ray of chest, decubitus view"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="codeSystemName">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="AlertStatusCode"/>
 *             &lt;enumeration value="HL7 ActCode"/>
 *             &lt;enumeration value="HL7ActClass"/>
 *             &lt;enumeration value="HL7RoleClass"/>
 *             &lt;enumeration value="HL7RoleCode"/>
 *             &lt;enumeration value="IHEActCode"/>
 *             &lt;enumeration value="LOINC"/>
 *             &lt;enumeration value="RxNorm"/>
 *             &lt;enumeration value="SNOMED CT"/>
 *             &lt;enumeration value="SNOMED-CT"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "originalText" })
@XmlRootElement(name = "code")
public class Code {

	protected String originalText;
	@XmlAttribute(name = "code")
	protected String code;
	@XmlAttribute(name = "codeSystem")
	protected String codeSystem;
	@XmlAttribute(name = "nullFlavor")
	protected String nullFlavor;
	@XmlAttribute(name = "displayName")
	protected String displayName;
	@XmlAttribute(name = "codeSystemName")
	protected String codeSystemName;

	/**
	 * Gets the value of the originalText property.
	 * 
	 * @return possible object is {@link OriginalText }
	 * 
	 */
	public String getOriginalText() {
		return originalText;
	}

	/**
	 * Sets the value of the originalText property.
	 * 
	 * @param value
	 *            allowed object is {@link OriginalText }
	 * 
	 */
	public void setOriginalText(String value) {
		this.originalText = value;
	}

	/**
	 * Gets the value of the code property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCode() {
		return code;
	}

	/**
	 * Sets the value of the code property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCode(String value) {
		this.code = value;
	}

	/**
	 * Gets the value of the codeSystem property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCodeSystem() {
		return codeSystem;
	}

	/**
	 * Sets the value of the codeSystem property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCodeSystem(String value) {
		this.codeSystem = value;
	}

	/**
	 * Gets the value of the nullFlavor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNullFlavor() {
		return nullFlavor;
	}

	/**
	 * Sets the value of the nullFlavor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNullFlavor(String value) {
		this.nullFlavor = value;
	}

	/**
	 * Gets the value of the displayName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDisplayName() {
		return displayName;
	}

	/**
	 * Sets the value of the displayName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDisplayName(String value) {
		this.displayName = value;
	}

	/**
	 * Gets the value of the codeSystemName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCodeSystemName() {
		return codeSystemName;
	}

	/**
	 * Sets the value of the codeSystemName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCodeSystemName(String value) {
		this.codeSystemName = value;
	}

}
