//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{urn:hl7-org:v3}structuredBody"/>
 *         &lt;element ref="{urn:hl7-org:v3}observation"/>
 *         &lt;element ref="{urn:hl7-org:v3}section"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "structuredBody", "observation", "section" })
@XmlRootElement(name = "component")
public class Component {

	protected StructuredBody structuredBody;
	protected Observation observation;
	protected Section section;

	/**
	 * Gets the value of the structuredBody property.
	 * 
	 * @return possible object is {@link StructuredBody }
	 * 
	 */
	public StructuredBody getStructuredBody() {
		return structuredBody;
	}

	/**
	 * Sets the value of the structuredBody property.
	 * 
	 * @param value
	 *            allowed object is {@link StructuredBody }
	 * 
	 */
	public void setStructuredBody(StructuredBody value) {
		this.structuredBody = value;
	}

	/**
	 * Gets the value of the observation property.
	 * 
	 * @return possible object is {@link Observation }
	 * 
	 */
	public Observation getObservation() {
		return observation;
	}

	/**
	 * Sets the value of the observation property.
	 * 
	 * @param value
	 *            allowed object is {@link Observation }
	 * 
	 */
	public void setObservation(Observation value) {
		this.observation = value;
	}

	/**
	 * Gets the value of the section property.
	 * 
	 * @return possible object is {@link Section }
	 * 
	 */
	public Section getSection() {
		return section;
	}

	/**
	 * Sets the value of the section property.
	 * 
	 * @param value
	 *            allowed object is {@link Section }
	 * 
	 */
	public void setSection(Section value) {
		this.section = value;
	}

}
