//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{urn:hl7-org:v3}substanceAdministration"/>
 *         &lt;element ref="{urn:hl7-org:v3}observation"/>
 *         &lt;element ref="{urn:hl7-org:v3}procedure"/>
 *         &lt;element ref="{urn:hl7-org:v3}organizer"/>
 *         &lt;element ref="{urn:hl7-org:v3}encounter"/>
 *         &lt;element ref="{urn:hl7-org:v3}act"/>
 *       &lt;/choice>
 *       &lt;attribute name="typeCode">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="DRIV"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "substanceAdministration", "observation", "procedure", "organizer", "encounter",
		"act" })
@XmlRootElement(name = "entry")
public class Entry {

	protected SubstanceAdministration substanceAdministration;
	protected Observation observation;
	protected Procedure procedure;
	protected Organizer organizer;
	protected Encounter encounter;
	protected Act act;
	@XmlAttribute(name = "typeCode")
	protected String typeCode;

	/**
	 * Gets the value of the substanceAdministration property.
	 * 
	 * @return possible object is {@link SubstanceAdministration }
	 * 
	 */
	public SubstanceAdministration getSubstanceAdministration() {
		return substanceAdministration;
	}

	/**
	 * Sets the value of the substanceAdministration property.
	 * 
	 * @param value
	 *            allowed object is {@link SubstanceAdministration }
	 * 
	 */
	public void setSubstanceAdministration(SubstanceAdministration value) {
		this.substanceAdministration = value;
	}

	/**
	 * Gets the value of the observation property.
	 * 
	 * @return possible object is {@link Observation }
	 * 
	 */
	public Observation getObservation() {
		return observation;
	}

	/**
	 * Sets the value of the observation property.
	 * 
	 * @param value
	 *            allowed object is {@link Observation }
	 * 
	 */
	public void setObservation(Observation value) {
		this.observation = value;
	}

	/**
	 * Gets the value of the procedure property.
	 * 
	 * @return possible object is {@link Procedure }
	 * 
	 */
	public Procedure getProcedure() {
		return procedure;
	}

	/**
	 * Sets the value of the procedure property.
	 * 
	 * @param value
	 *            allowed object is {@link Procedure }
	 * 
	 */
	public void setProcedure(Procedure value) {
		this.procedure = value;
	}

	/**
	 * Gets the value of the organizer property.
	 * 
	 * @return possible object is {@link Organizer }
	 * 
	 */
	public Organizer getOrganizer() {
		return organizer;
	}

	/**
	 * Sets the value of the organizer property.
	 * 
	 * @param value
	 *            allowed object is {@link Organizer }
	 * 
	 */
	public void setOrganizer(Organizer value) {
		this.organizer = value;
	}

	/**
	 * Gets the value of the encounter property.
	 * 
	 * @return possible object is {@link Encounter }
	 * 
	 */
	public Encounter getEncounter() {
		return encounter;
	}

	/**
	 * Sets the value of the encounter property.
	 * 
	 * @param value
	 *            allowed object is {@link Encounter }
	 * 
	 */
	public void setEncounter(Encounter value) {
		this.encounter = value;
	}

	/**
	 * Gets the value of the act property.
	 * 
	 * @return possible object is {@link Act }
	 * 
	 */
	public Act getAct() {
		return act;
	}

	/**
	 * Sets the value of the act property.
	 * 
	 * @param value
	 *            allowed object is {@link Act }
	 * 
	 */
	public void setAct(Act value) {
		this.act = value;
	}

	/**
	 * Gets the value of the typeCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTypeCode() {
		return typeCode;
	}

	/**
	 * Sets the value of the typeCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTypeCode(String value) {
		this.typeCode = value;
	}

}
