//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{urn:hl7-org:v3}observation"/>
 *         &lt;element ref="{urn:hl7-org:v3}supply"/>
 *         &lt;element ref="{urn:hl7-org:v3}act"/>
 *       &lt;/choice>
 *       &lt;attribute name="typeCode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="COMP"/>
 *             &lt;enumeration value="MFST"/>
 *             &lt;enumeration value="REFR"/>
 *             &lt;enumeration value="SUBJ"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="inversionInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "observation", "supply", "act" })
@XmlRootElement(name = "entryRelationship")
public class EntryRelationship {

	protected Observation observation;
	protected Supply supply;
	protected Act act;
	@XmlAttribute(name = "typeCode", required = true)
	protected String typeCode;
	@XmlAttribute(name = "inversionInd")
	protected Boolean inversionInd;

	/**
	 * Gets the value of the observation property.
	 * 
	 * @return possible object is {@link Observation }
	 * 
	 */
	public Observation getObservation() {
		return observation;
	}

	/**
	 * Sets the value of the observation property.
	 * 
	 * @param value
	 *            allowed object is {@link Observation }
	 * 
	 */
	public void setObservation(Observation value) {
		this.observation = value;
	}

	/**
	 * Gets the value of the supply property.
	 * 
	 * @return possible object is {@link Supply }
	 * 
	 */
	public Supply getSupply() {
		return supply;
	}

	/**
	 * Sets the value of the supply property.
	 * 
	 * @param value
	 *            allowed object is {@link Supply }
	 * 
	 */
	public void setSupply(Supply value) {
		this.supply = value;
	}

	/**
	 * Gets the value of the act property.
	 * 
	 * @return possible object is {@link Act }
	 * 
	 */
	public Act getAct() {
		return act;
	}

	/**
	 * Sets the value of the act property.
	 * 
	 * @param value
	 *            allowed object is {@link Act }
	 * 
	 */
	public void setAct(Act value) {
		this.act = value;
	}

	/**
	 * Gets the value of the typeCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTypeCode() {
		return typeCode;
	}

	/**
	 * Sets the value of the typeCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTypeCode(String value) {
		this.typeCode = value;
	}

	/**
	 * Gets the value of the inversionInd property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isInversionInd() {
		return inversionInd;
	}

	/**
	 * Sets the value of the inversionInd property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setInversionInd(Boolean value) {
		this.inversionInd = value;
	}

}
