//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="root">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="067f1f86-9cb5-4aa8-1f9e-d108f89618f6"/>
 *             &lt;enumeration value="1085ff61-dfcf-47e6-2d88-58a900784920"/>
 *             &lt;enumeration value="17e7e5f2-f258-4efb-3fbc-ce78a7f966e1"/>
 *             &lt;enumeration value="1b6095c9-0315-4af0-a6b7-9d79713cd0c2"/>
 *             &lt;enumeration value="1ba9c5ee-60b9-4bb8-348d-764ca31cda09"/>
 *             &lt;enumeration value="2.16.840.1.113883.3.3265"/>
 *             &lt;enumeration value="2.16.840.1.113883.4.6"/>
 *             &lt;enumeration value="22e7ab61-8e82-4a1e-dcab-abf0f1416d00"/>
 *             &lt;enumeration value="23a479bb-e38b-4d46-3bbc-eb3b801bcfb4"/>
 *             &lt;enumeration value="2bf6bca8-eabe-4b0c-5084-e70a100a760f"/>
 *             &lt;enumeration value="3b2f22a0-554d-4a8f-81a1-848580028aec"/>
 *             &lt;enumeration value="3d554195-d719-4c24-528e-58a071ef39c1"/>
 *             &lt;enumeration value="3ed0b285-954a-48b4-6c9a-c2830e8860d8"/>
 *             &lt;enumeration value="3ff12072-3bc4-47e6-c49c-be9267022cfa"/>
 *             &lt;enumeration value="4ba0f23c-1086-459e-4cb0-f0afc8354d5d"/>
 *             &lt;enumeration value="56d3fa86-3f6e-48bd-80b0-edc790fa94e8"/>
 *             &lt;enumeration value="6477d56f-8d6b-4729-f2ae-d0dbaad169ed"/>
 *             &lt;enumeration value="692f98fa-b42b-4a75-c694-152e18c7c9d8"/>
 *             &lt;enumeration value="6e50d4aa-f86d-4b96-52a6-ea966b2dd14e"/>
 *             &lt;enumeration value="7095ebec-6bb3-47b1-f48f-bc22c92fd3dc"/>
 *             &lt;enumeration value="713aac90-a626-412e-129f-d14c766af46e"/>
 *             &lt;enumeration value="74832e2a-6eb4-41fd-92be-db24f065670a"/>
 *             &lt;enumeration value="a6adabe3-609f-471b-38a0-b4a6f897d350"/>
 *             &lt;enumeration value="a97c1a87-2e5b-4474-5dba-dbcb7ed540ce"/>
 *             &lt;enumeration value="aa8b245d-79cf-4cb2-32aa-2c18a6012d00"/>
 *             &lt;enumeration value="ab5923ed-ddb7-439b-0dae-515682b3bffe"/>
 *             &lt;enumeration value="aff07bd3-2717-4e58-c6bb-f392c3f1be8b"/>
 *             &lt;enumeration value="b4ef7f41-f3ff-449f-2b99-1c92f4c8fcef"/>
 *             &lt;enumeration value="d69a7220-1878-420f-3488-49bc04f99970"/>
 *             &lt;enumeration value="d7c9c74b-3c38-47c3-ceaf-7488dbb7ba4a"/>
 *             &lt;enumeration value="d85a8cb3-b1d1-44a4-5abe-c3a7a8786d30"/>
 *             &lt;enumeration value="dea60766-286f-435b-4193-fccabcd51a89"/>
 *             &lt;enumeration value="ed3228c3-5e98-40ac-4a85-e6c632483b82"/>
 *             &lt;enumeration value="ed41a673-0fa2-432d-aea2-369f2b068227"/>
 *             &lt;enumeration value="edeb51f4-f13e-4548-f8af-1a9aa878a574"/>
 *             &lt;enumeration value="f1476540-15d7-4f66-8db9-793e9e009407"/>
 *             &lt;enumeration value="f1d9b90e-2ee8-457f-62b4-3a4af8c84943"/>
 *             &lt;enumeration value="f75389a6-d217-426b-e795-ff63141c41c3"/>
 *             &lt;enumeration value="fb272a41-54a5-4aa6-d6a5-20dc6f2e32dd"/>
 *             &lt;enumeration value="febd536c-f6e2-40f6-77af-36aaa5ae2cee"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="extension">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="000000000"/>
 *             &lt;enumeration value="0000000048"/>
 *             &lt;enumeration value="0000000049"/>
 *             &lt;enumeration value="1376593871"/>
 *             &lt;enumeration value="1447351747"/>
 *             &lt;enumeration value="1619932845"/>
 *             &lt;enumeration value="1720034846"/>
 *             &lt;enumeration value="M000001146"/>
 *             &lt;enumeration value="NI"/>
 *             &lt;enumeration value="UPD-BG1"/>
 *             &lt;enumeration value="V000018119"/>
 *             &lt;enumeration value="V000018481"/>
 *             &lt;enumeration value="V000018853"/>
 *             &lt;enumeration value="V000019034"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="nullFlavor">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="NA"/>
 *             &lt;enumeration value="NI"/>
 *             &lt;enumeration value="UNK"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "id")
public class Id {

	@XmlAttribute(name = "root")
	protected String root;
	@XmlAttribute(name = "extension")
	protected String extension;
	@XmlAttribute(name = "nullFlavor")
	protected String nullFlavor;

	/**
	 * Gets the value of the root property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRoot() {
		return root;
	}

	/**
	 * Sets the value of the root property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRoot(String value) {
		this.root = value;
	}

	/**
	 * Gets the value of the extension property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getExtension() {
		return extension;
	}

	/**
	 * Sets the value of the extension property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setExtension(String value) {
		this.extension = value;
	}

	/**
	 * Gets the value of the nullFlavor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNullFlavor() {
		return nullFlavor;
	}

	/**
	 * Sets the value of the nullFlavor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNullFlavor(String value) {
		this.nullFlavor = value;
	}

}
