//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}languageCode"/>
 *         &lt;element ref="{urn:hl7-org:v3}preferenceInd"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "languageCode", "preferenceInd" })
@XmlRootElement(name = "languageCommunication")
public class LanguageCommunication {

	@XmlElement(required = true)
	protected LanguageCode languageCode;
	@XmlElement(required = true)
	protected PreferenceInd preferenceInd;

	/**
	 * Gets the value of the languageCode property.
	 * 
	 * @return possible object is {@link LanguageCode }
	 * 
	 */
	public LanguageCode getLanguageCode() {
		return languageCode;
	}

	/**
	 * Sets the value of the languageCode property.
	 * 
	 * @param value
	 *            allowed object is {@link LanguageCode }
	 * 
	 */
	public void setLanguageCode(LanguageCode value) {
		this.languageCode = value;
	}

	/**
	 * Gets the value of the preferenceInd property.
	 * 
	 * @return possible object is {@link PreferenceInd }
	 * 
	 */
	public PreferenceInd getPreferenceInd() {
		return preferenceInd;
	}

	/**
	 * Sets the value of the preferenceInd property.
	 * 
	 * @param value
	 *            allowed object is {@link PreferenceInd }
	 * 
	 */
	public void setPreferenceInd(PreferenceInd value) {
		this.preferenceInd = value;
	}

}
