//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.05 at 11:21:56 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}time"/>
 *         &lt;element ref="{urn:hl7-org:v3}signatureCode"/>
 *         &lt;element ref="{urn:hl7-org:v3}assignedEntity"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "time", "signatureCode", "assignedEntity", "addr", "telecom" })
@XmlRootElement(name = "legalAuthenticator")
public class LegalAuthenticator {

	@XmlElement(required = true)
	protected Time time;
	@XmlElement(required = true)
	protected SignatureCode signatureCode;
	@XmlElement(required = true)
	protected AssignedEntity assignedEntity;
	@XmlElement(required = true)
	protected Telecom telecom;
	@XmlElement(required = true)
	protected Addr addr;

	public Addr getAddr() {
		return addr;
	}

	/**
	 * Sets the value of the addr property.
	 * 
	 * @param value
	 *            allowed object is {@link Addr }
	 * 
	 */
	public void setAddr(Addr value) {
		this.addr = value;
	}

	/**
	 * Gets the value of the telecom property.
	 * 
	 * @return possible object is {@link Telecom }
	 * 
	 */
	public Telecom getTelecom() {
		return telecom;
	}

	/**
	 * Sets the value of the telecom property.
	 * 
	 * @param value
	 *            allowed object is {@link Telecom }
	 * 
	 */
	public void setTelecom(Telecom value) {
		this.telecom = value;
	}

	/**
	 * Gets the value of the time property.
	 * 
	 * @return possible object is {@link Time }
	 * 
	 */
	public Time getTime() {
		return time;
	}

	/**
	 * Sets the value of the time property.
	 * 
	 * @param string
	 *            allowed object is {@link Time }
	 * 
	 */
	public void setTime(Time string) {
		this.time = string;
	}

	/**
	 * Gets the value of the signatureCode property.
	 * 
	 * @return possible object is {@link SignatureCode }
	 * 
	 */
	public SignatureCode getSignatureCode() {
		return signatureCode;
	}

	/**
	 * Sets the value of the signatureCode property.
	 * 
	 * @param value
	 *            allowed object is {@link SignatureCode }
	 * 
	 */
	public void setSignatureCode(SignatureCode value) {
		this.signatureCode = value;
	}

	/**
	 * Gets the value of the assignedEntity property.
	 * 
	 * @return possible object is {@link AssignedEntity }
	 * 
	 */
	public AssignedEntity getAssignedEntity() {
		return assignedEntity;
	}

	/**
	 * Sets the value of the assignedEntity property.
	 * 
	 * @param value
	 *            allowed object is {@link AssignedEntity }
	 * 
	 */
	public void setAssignedEntity(AssignedEntity value) {
		this.assignedEntity = value;
	}

}
