//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}templateId"/>
 *         &lt;element ref="{urn:hl7-org:v3}manufacturedMaterial"/>
 *       &lt;/sequence>
 *       &lt;attribute name="classCode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="MANU"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "templateId", "manufacturedMaterial" })
@XmlRootElement(name = "manufacturedProduct")
public class ManufacturedProduct {

	@XmlElement(required = true)
	protected TemplateId templateId;
	@XmlElement(required = true)
	protected ManufacturedMaterial manufacturedMaterial;
	@XmlAttribute(name = "classCode", required = true)
	protected String classCode;

	/**
	 * Gets the value of the templateId property.
	 * 
	 * @return possible object is {@link TemplateId }
	 * 
	 */
	public TemplateId getTemplateId() {
		return templateId;
	}

	/**
	 * Sets the value of the templateId property.
	 * 
	 * @param value
	 *            allowed object is {@link TemplateId }
	 * 
	 */
	public void setTemplateId(TemplateId value) {
		this.templateId = value;
	}

	/**
	 * Gets the value of the manufacturedMaterial property.
	 * 
	 * @return possible object is {@link ManufacturedMaterial }
	 * 
	 */
	public ManufacturedMaterial getManufacturedMaterial() {
		return manufacturedMaterial;
	}

	/**
	 * Sets the value of the manufacturedMaterial property.
	 * 
	 * @param value
	 *            allowed object is {@link ManufacturedMaterial }
	 * 
	 */
	public void setManufacturedMaterial(ManufacturedMaterial value) {
		this.manufacturedMaterial = value;
	}

	/**
	 * Gets the value of the classCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClassCode() {
		return classCode;
	}

	/**
	 * Sets the value of the classCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setClassCode(String value) {
		this.classCode = value;
	}

}
