//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{urn:hl7-org:v3}given" maxOccurs="unbounded"/>
 *         &lt;element ref="{urn:hl7-org:v3}family"/>
 *         &lt;element ref="{urn:hl7-org:v3}suffix" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "given", "family", "content" })
@XmlRootElement(name = "name")
public class Name {

	/*
	 * @XmlElementRefs({
	 * 
	 * @XmlElementRef(name = "family", namespace = "urn:hl7-org:v3", type =
	 * JAXBElement.class),
	 * 
	 * @XmlElementRef(name = "suffix", namespace = "urn:hl7-org:v3", type =
	 * Suffix.class),
	 * 
	 * @XmlElementRef(name = "given", namespace = "urn:hl7-org:v3", type =
	 * Given.class) })
	 */
	@XmlMixed
	protected List<Object> content;

	@XmlElement(name = "given")
	protected String given;

	@XmlElement(name = "family")
	protected String family;

	public List<Object> getContent() {
		return content;
	}

	public void setContent(List<Object> content) {
		this.content = content;
	}

	public String getGiven() {
		return given;
	}

	public void setGiven(String given) {
		this.given = given;
	}

	public String getFamily() {
		return family;
	}

	public void setFamily(String family) {
		this.family = family;
	}
	/**
	 * Gets the value of the content property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the content property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getContent().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Given }
	 * {@link Suffix } {@link JAXBElement }{@code <}{@link String }{@code >}
	 * {@link String }
	 * 
	 * 
	 */
}
