//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.hl7.v3 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _EffectiveTime_QNAME = new QName("urn:hl7-org:v3", "effectiveTime");
	private final static QName _Value_QNAME = new QName("urn:hl7-org:v3", "value");
	private final static QName _State_QNAME = new QName("urn:hl7-org:v3", "state");
	private final static QName _Th_QNAME = new QName("urn:hl7-org:v3", "th");
	private final static QName _City_QNAME = new QName("urn:hl7-org:v3", "city");
	private final static QName _SoftwareName_QNAME = new QName("urn:hl7-org:v3", "softwareName");
	private final static QName _ManufacturerModelName_QNAME = new QName("urn:hl7-org:v3", "manufacturerModelName");
	private final static QName _PostalCode_QNAME = new QName("urn:hl7-org:v3", "postalCode");
	private final static QName _StreetAddressLine_QNAME = new QName("urn:hl7-org:v3", "streetAddressLine");
	private final static QName _Title_QNAME = new QName("urn:hl7-org:v3", "title");
	private final static QName _Content_QNAME = new QName("urn:hl7-org:v3", "content");
	private final static QName _Family_QNAME = new QName("urn:hl7-org:v3", "family");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: org.hl7.v3
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link AssignedCustodian }
	 * 
	 */
	public AssignedCustodian createAssignedCustodian() {
		return new AssignedCustodian();
	}

	/**
	 * Create an instance of {@link RepresentedCustodianOrganization }
	 * 
	 */
	public RepresentedCustodianOrganization createRepresentedCustodianOrganization() {
		return new RepresentedCustodianOrganization();
	}

	/**
	 * Create an instance of {@link Id }
	 * 
	 */
	public Id createId() {
		return new Id();
	}

	/**
	 * Create an instance of {@link Name }
	 * 
	 */
	public Name createName() {
		return new Name();
	}

	/**
	 * Create an instance of {@link Given }
	 * 
	 */
	public Given createGiven() {
		return new Given();
	}

	/**
	 * Create an instance of {@link Suffix }
	 * 
	 */
	public Suffix createSuffix() {
		return new Suffix();
	}

	/**
	 * Create an instance of {@link Telecom }
	 * 
	 */
	public Telecom createTelecom() {
		return new Telecom();
	}

	/**
	 * Create an instance of {@link Addr }
	 * 
	 */
	public Addr createAddr() {
		return new Addr();
	}

	/**
	 * Create an instance of {@link LanguageCommunication }
	 * 
	 */
	public LanguageCommunication createLanguageCommunication() {
		return new LanguageCommunication();
	}

	/**
	 * Create an instance of {@link LanguageCode }
	 * 
	 */
	public LanguageCode createLanguageCode() {
		return new LanguageCode();
	}

	/**
	 * Create an instance of {@link PreferenceInd }
	 * 
	 */
	public PreferenceInd createPreferenceInd() {
		return new PreferenceInd();
	}

	/**
	 * Create an instance of {@link Tr }
	 * 
	 */
	public Tr createTr() {
		return new Tr();
	}

	/**
	 * Create an instance of {@link Td }
	 * 
	 */
	public Td createTd() {
		return new Td();
	}

	/**
	 * Create an instance of {@link RecordTarget }
	 * 
	 */
	public RecordTarget createRecordTarget() {
		return new RecordTarget();
	}

	/**
	 * Create an instance of {@link PatientRole }
	 * 
	 */
	public PatientRole createPatientRole() {
		return new PatientRole();
	}

	/**
	 * Create an instance of {@link Patient }
	 * 
	 */
	public Patient createPatient() {
		return new Patient();
	}

	/**
	 * Create an instance of {@link AdministrativeGenderCode }
	 * 
	 */
	public AdministrativeGenderCode createAdministrativeGenderCode() {
		return new AdministrativeGenderCode();
	}

	/**
	 * Create an instance of {@link BirthTime }
	 * 
	 */
	public BirthTime createBirthTime() {
		return new BirthTime();
	}

	/**
	 * Create an instance of {@link RaceCode }
	 * 
	 */
	public RaceCode createRaceCode() {
		return new RaceCode();
	}

	/**
	 * Create an instance of {@link EthnicGroupCode }
	 * 
	 */
	public EthnicGroupCode createEthnicGroupCode() {
		return new EthnicGroupCode();
	}

	/**
	 * Create an instance of {@link Encounter }
	 * 
	 */
	public Encounter createEncounter() {
		return new Encounter();
	}

	/**
	 * Create an instance of {@link TemplateId }
	 * 
	 */
	public TemplateId createTemplateId() {
		return new TemplateId();
	}

	/**
	 * Create an instance of {@link Code }
	 * 
	 */
	public Code createCode() {
		return new Code();
	}

	/**
	 * Create an instance of {@link OriginalText }
	 * 
	 */
	public OriginalText createOriginalText() {
		return new OriginalText();
	}

	/**
	 * Create an instance of {@link Reference }
	 * 
	 */
	public Reference createReference() {
		return new Reference();
	}

	/**
	 * Create an instance of {@link TEffectiveTime }
	 * 
	 */
	public TEffectiveTime createTEffectiveTime() {
		return new TEffectiveTime();
	}

	/**
	 * Create an instance of {@link Performer }
	 * 
	 */
	public Performer createPerformer() {
		return new Performer();
	}

	/**
	 * Create an instance of {@link FunctionCode }
	 * 
	 */
	public FunctionCode createFunctionCode() {
		return new FunctionCode();
	}

	/**
	 * Create an instance of {@link AssignedEntity }
	 * 
	 */
	public AssignedEntity createAssignedEntity() {
		return new AssignedEntity();
	}

	/**
	 * Create an instance of {@link AssignedPerson }
	 * 
	 */
	public AssignedPerson createAssignedPerson() {
		return new AssignedPerson();
	}

	/**
	 * Create an instance of {@link RepresentedOrganization }
	 * 
	 */
	public RepresentedOrganization createRepresentedOrganization() {
		return new RepresentedOrganization();
	}

	/**
	 * Create an instance of {@link SubstanceAdministration }
	 * 
	 */
	public SubstanceAdministration createSubstanceAdministration() {
		return new SubstanceAdministration();
	}

	/**
	 * Create an instance of {@link StatusCode }
	 * 
	 */
	public StatusCode createStatusCode() {
		return new StatusCode();
	}

	/**
	 * Create an instance of {@link Consumable }
	 * 
	 */
	public Consumable createConsumable() {
		return new Consumable();
	}

	/**
	 * Create an instance of {@link ManufacturedProduct }
	 * 
	 */
	public ManufacturedProduct createManufacturedProduct() {
		return new ManufacturedProduct();
	}

	/**
	 * Create an instance of {@link ManufacturedMaterial }
	 * 
	 */
	public ManufacturedMaterial createManufacturedMaterial() {
		return new ManufacturedMaterial();
	}

	/**
	 * Create an instance of {@link Text }
	 * 
	 */
	public Text createText() {
		return new Text();
	}

	/**
	 * Create an instance of {@link Table }
	 * 
	 */
	public Table createTable() {
		return new Table();
	}

	/**
	 * Create an instance of {@link Thead }
	 * 
	 */
	public Thead createThead() {
		return new Thead();
	}

	/**
	 * Create an instance of {@link Tbody }
	 * 
	 */
	public Tbody createTbody() {
		return new Tbody();
	}

	/**
	 * Create an instance of {@link RepeatNumber }
	 * 
	 */
	public RepeatNumber createRepeatNumber() {
		return new RepeatNumber();
	}

	/**
	 * Create an instance of {@link DoseQuantity }
	 * 
	 */
	public DoseQuantity createDoseQuantity() {
		return new DoseQuantity();
	}

	/**
	 * Create an instance of {@link EntryRelationship }
	 * 
	 */
	public EntryRelationship createEntryRelationship() {
		return new EntryRelationship();
	}

	/**
	 * Create an instance of {@link Observation }
	 * 
	 */
	public Observation createObservation() {
		return new Observation();
	}

	/**
	 * Create an instance of {@link TValue }
	 * 
	 */
	public TValue createTValue() {
		return new TValue();
	}

	/**
	 * Create an instance of {@link Participant }
	 * 
	 */
	public Participant createParticipant() {
		return new Participant();
	}

	/**
	 * Create an instance of {@link Time }
	 * 
	 */
	public Time createTime() {
		return new Time();
	}

	/**
	 * Create an instance of {@link Low }
	 * 
	 */
	public Low createLow() {
		return new Low();
	}

	/**
	 * Create an instance of {@link High }
	 * 
	 */
	public High createHigh() {
		return new High();
	}

	/**
	 * Create an instance of {@link ParticipantRole }
	 * 
	 */
	public ParticipantRole createParticipantRole() {
		return new ParticipantRole();
	}

	/**
	 * Create an instance of {@link PlayingEntity }
	 * 
	 */
	public PlayingEntity createPlayingEntity() {
		return new PlayingEntity();
	}

	/**
	 * Create an instance of {@link AssociatedEntity }
	 * 
	 */
	public AssociatedEntity createAssociatedEntity() {
		return new AssociatedEntity();
	}

	/**
	 * Create an instance of {@link AssociatedPerson }
	 * 
	 */
	public AssociatedPerson createAssociatedPerson() {
		return new AssociatedPerson();
	}

	/**
	 * Create an instance of {@link InterpretationCode }
	 * 
	 */
	public InterpretationCode createInterpretationCode() {
		return new InterpretationCode();
	}

	/**
	 * Create an instance of {@link ReferenceRange }
	 * 
	 */
	public ReferenceRange createReferenceRange() {
		return new ReferenceRange();
	}

	/**
	 * Create an instance of {@link ObservationRange }
	 * 
	 */
	public ObservationRange createObservationRange() {
		return new ObservationRange();
	}

	/**
	 * Create an instance of {@link Supply }
	 * 
	 */
	public Supply createSupply() {
		return new Supply();
	}

	/**
	 * Create an instance of {@link Quantity }
	 * 
	 */
	public Quantity createQuantity() {
		return new Quantity();
	}

	/**
	 * Create an instance of {@link Product }
	 * 
	 */
	public Product createProduct() {
		return new Product();
	}

	/**
	 * Create an instance of {@link Author }
	 * 
	 */
	public Author createAuthor() {
		return new Author();
	}

	/**
	 * Create an instance of {@link AssignedAuthor }
	 * 
	 */
	public AssignedAuthor createAssignedAuthor() {
		return new AssignedAuthor();
	}

	/**
	 * Create an instance of {@link AssignedAuthoringDevice }
	 * 
	 */
	public AssignedAuthoringDevice createAssignedAuthoringDevice() {
		return new AssignedAuthoringDevice();
	}

	/**
	 * Create an instance of {@link Act }
	 * 
	 */
	public Act createAct() {
		return new Act();
	}

	/**
	 * Create an instance of {@link Component }
	 * 
	 */
	public Component createComponent() {
		return new Component();
	}

	/**
	 * Create an instance of {@link StructuredBody }
	 * 
	 */
	public StructuredBody createStructuredBody() {
		return new StructuredBody();
	}

	/**
	 * Create an instance of {@link Section }
	 * 
	 */
	public Section createSection() {
		return new Section();
	}

	/**
	 * Create an instance of {@link Entry }
	 * 
	 */
	public Entry createEntry() {
		return new Entry();
	}

	/**
	 * Create an instance of {@link Procedure }
	 * 
	 */
	public Procedure createProcedure() {
		return new Procedure();
	}

	/**
	 * Create an instance of {@link Organizer }
	 * 
	 */
	public Organizer createOrganizer() {
		return new Organizer();
	}

	/**
	 * Create an instance of {@link ClinicalDocument }
	 * 
	 */
	public ClinicalDocument createClinicalDocument() {
		return new ClinicalDocument();
	}

	/**
	 * Create an instance of {@link RealmCode }
	 * 
	 */
	public RealmCode createRealmCode() {
		return new RealmCode();
	}

	/**
	 * Create an instance of {@link TypeId }
	 * 
	 */
	public TypeId createTypeId() {
		return new TypeId();
	}

	/**
	 * Create an instance of {@link ConfidentialityCode }
	 * 
	 */
	public ConfidentialityCode createConfidentialityCode() {
		return new ConfidentialityCode();
	}

	/**
	 * Create an instance of {@link Custodian }
	 * 
	 */
	public Custodian createCustodian() {
		return new Custodian();
	}

	/**
	 * Create an instance of {@link DocumentationOf }
	 * 
	 */
	public DocumentationOf createDocumentationOf() {
		return new DocumentationOf();
	}

	/**
	 * Create an instance of {@link ServiceEvent }
	 * 
	 */
	public ServiceEvent createServiceEvent() {
		return new ServiceEvent();
	}

	/**
	 * Create an instance of {@link CE }
	 * 
	 */
	public CE createCE() {
		return new CE();
	}

	/**
	 * Create an instance of {@link PQ }
	 * 
	 */
	public PQ createPQ() {
		return new PQ();
	}

	/**
	 * Create an instance of {@link CD }
	 * 
	 */
	public CD createCD() {
		return new CD();
	}

	/**
	 * Create an instance of {@link IVLTS }
	 * 
	 */
	public IVLTS createIVLTS() {
		return new IVLTS();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link TEffectiveTime }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:hl7-org:v3", name = "effectiveTime")
	public JAXBElement<TEffectiveTime> createEffectiveTime(TEffectiveTime value) {
		return new JAXBElement<TEffectiveTime>(_EffectiveTime_QNAME, TEffectiveTime.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link TValue }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:hl7-org:v3", name = "value")
	public JAXBElement<TValue> createValue(TValue value) {
		return new JAXBElement<TValue>(_Value_QNAME, TValue.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:hl7-org:v3", name = "state")
	public JAXBElement<String> createState(String value) {
		return new JAXBElement<String>(_State_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:hl7-org:v3", name = "th")
	public JAXBElement<String> createTh(String value) {
		return new JAXBElement<String>(_Th_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:hl7-org:v3", name = "city")
	public JAXBElement<String> createCity(String value) {
		return new JAXBElement<String>(_City_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:hl7-org:v3", name = "softwareName")
	public JAXBElement<String> createSoftwareName(String value) {
		return new JAXBElement<String>(_SoftwareName_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:hl7-org:v3", name = "manufacturerModelName")
	public JAXBElement<String> createManufacturerModelName(String value) {
		return new JAXBElement<String>(_ManufacturerModelName_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:hl7-org:v3", name = "postalCode")
	public JAXBElement<Integer> createPostalCode(Integer value) {
		return new JAXBElement<Integer>(_PostalCode_QNAME, Integer.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:hl7-org:v3", name = "streetAddressLine")
	public JAXBElement<String> createStreetAddressLine(String value) {
		return new JAXBElement<String>(_StreetAddressLine_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:hl7-org:v3", name = "title")
	public JAXBElement<String> createTitle(String value) {
		return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:hl7-org:v3", name = "content")
	public JAXBElement<String> createContent(String value) {
		return new JAXBElement<String>(_Content_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:hl7-org:v3", name = "family")
	public JAXBElement<String> createFamily(String value) {
		return new JAXBElement<String>(_Family_QNAME, String.class, null, value);
	}

}
