//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.05 at 11:21:56 PM IST 
//
package com.versawork.http.ccd;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}templateId" maxOccurs="unbounded"/>
 *         &lt;element ref="{urn:hl7-org:v3}id"/>
 *         &lt;element ref="{urn:hl7-org:v3}code"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{urn:hl7-org:v3}text"/>
 *             &lt;element ref="{urn:hl7-org:v3}statusCode"/>
 *             &lt;element ref="{urn:hl7-org:v3}effectiveTime"/>
 *             &lt;element ref="{urn:hl7-org:v3}priorityCode"/>
 *             &lt;element ref="{urn:hl7-org:v3}value"/>
 *             &lt;element ref="{urn:hl7-org:v3}entryRelationship"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{urn:hl7-org:v3}statusCode"/>
 *             &lt;element ref="{urn:hl7-org:v3}value"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="moodCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="classCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "observation", propOrder = { "templateId", "id", "code", "statusCode", "effectiveTime", "value",
		"participant", "entryRelationship", "interpretationCode", "referenceRange"

})
@XmlRootElement(name = "observation")
public class Observation {

	/*
	 * @XmlElementRefs({
	 * 
	 * @XmlElementRef(name = "code", namespace = "urn:hl7-org:v3", type =
	 * Code.class, required = false),
	 * 
	 * @XmlElementRef(name = "templateId", namespace = "urn:hl7-org:v3", type =
	 * TemplateId.class, required = false),
	 * 
	 * @XmlElementRef(name = "entryRelationship", namespace = "urn:hl7-org:v3",
	 * type = EntryRelationship.class, required = false),
	 * 
	 * @XmlElementRef(name = "effectiveTime", namespace = "urn:hl7-org:v3", type
	 * = JAXBElement.class, required = false),
	 * 
	 * @XmlElementRef(name = "id", namespace = "urn:hl7-org:v3", type =
	 * Id.class, required = false),
	 * 
	 * @XmlElementRef(name = "priorityCode", namespace = "urn:hl7-org:v3", type
	 * = PriorityCode.class, required = false),
	 * 
	 * @XmlElementRef(name = "value", namespace = "urn:hl7-org:v3", type =
	 * JAXBElement.class, required = false),
	 * 
	 * @XmlElementRef(name = "statusCode", namespace = "urn:hl7-org:v3", type =
	 * StatusCode.class, required = false),
	 * 
	 * @XmlElementRef(name = "text", namespace = "urn:hl7-org:v3", type =
	 * Text.class, required = false) })
	 */
	/* protected List<Object> content; */

	@XmlElement
	protected List<TemplateId> templateId;

	@XmlElement
	protected Id id;

	@XmlElement
	protected Code code;

	@XmlElement
	protected Value value;

	@XmlElement
	protected List<EntryRelationship> entryRelationship;

	@XmlElement
	protected StatusCode statusCode;

	@XmlElement
	protected EffectiveTime effectiveTime;

	@XmlElement
	protected Participant participant;

	@XmlElement
	protected InterpretationCode interpretationCode;

	@XmlElement
	protected ReferenceRange referenceRange;

	@XmlAttribute(name = "classCode", required = true)
	protected String classCode;
	@XmlAttribute(name = "moodCode", required = true)
	protected String moodCode;

	public ReferenceRange getReferenceRange() {
		return referenceRange;
	}

	public void setReferenceRange(ReferenceRange referenceRange) {
		this.referenceRange = referenceRange;
	}

	public InterpretationCode getInterpretationCode() {
		return interpretationCode;
	}

	public void setInterpretationCode(InterpretationCode interpretationCode) {
		this.interpretationCode = interpretationCode;
	}

	public Participant getParticipant() {
		return participant;
	}

	public void setParticipant(Participant participant) {
		this.participant = participant;
	}

	public Value getValue() {
		return value;
	}

	public void setValue(Value value) {
		this.value = value;
	}

	public List<TemplateId> getTemplateId() {

		if (this.templateId == null) {
			return new ArrayList<TemplateId>();
		}
		return this.templateId;
	}

	public void setTemplateId(List<TemplateId> value) {
		this.templateId = value;
	}

	public Id getId() {
		return id;
	}

	public void setId(Id id) {
		this.id = id;
	}

	public Code getCode() {
		return code;
	}

	public void setCode(Code code) {
		this.code = code;
	}

	public List<EntryRelationship> getEntryRelationship() {
		if (entryRelationship == null) {
			return new ArrayList<EntryRelationship>();
		}
		return this.entryRelationship;
	}

	public void setEntryRelationship(List<EntryRelationship> entryRelationship) {
		this.entryRelationship = entryRelationship;
	}

	public StatusCode getStatusCode() {
		return statusCode;
	}

	public void setStatusCode(StatusCode statusCode) {
		this.statusCode = statusCode;
	}

	public EffectiveTime getEffectiveTime() {
		return effectiveTime;
	}

	public void setEffectiveTime(EffectiveTime effectiveTime) {
		this.effectiveTime = effectiveTime;
	}

	/**
	 * Gets the rest of the content model.
	 * 
	 * <p>
	 * You are getting this "catch-all" property because of the following
	 * reason: The field name "StatusCode" is used by two different parts of a
	 * schema. See: line 333 of
	 * file:/D:/Ires%20Lab/VersaWorks/VersaworksQRDAI/src/XSD/CDA.xsd line 326
	 * of file:/D:/Ires%20Lab/VersaWorks/VersaworksQRDAI/src/XSD/CDA.xsd
	 * <p>
	 * To get rid of this property, apply a property customization to one of
	 * both of the following declarations to change their names: Gets the value
	 * of the content property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the content property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getContent().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link TemplateId } {@link Code } {@link JAXBElement }{@code <}
	 * {@link EffectiveTime }{@code >} {@link EntryRelationship } {@link Id }
	 * {@link PriorityCode } {@link JAXBElement }{@code <}{@link Value }{@code >}
	 * {@link StatusCode } {@link Text }
	 * 
	 * 
	 */
	/*
	 * public List<Object> getContent() { if (content == null) { content = new
	 * ArrayList<Object>(); } return this.content; }
	 */
	/**
	 * Gets the value of the moodCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMoodCode() {
		return moodCode;
	}

	/**
	 * Sets the value of the moodCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMoodCode(String value) {
		this.moodCode = value;
	}

	/**
	 * Gets the value of the classCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClassCode() {
		return classCode;
	}

	/**
	 * Sets the value of the classCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setClassCode(String value) {
		this.classCode = value;
	}

}
