//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}templateId"/>
 *         &lt;element ref="{urn:hl7-org:v3}id"/>
 *         &lt;element ref="{urn:hl7-org:v3}code"/>
 *         &lt;element ref="{urn:hl7-org:v3}statusCode"/>
 *         &lt;element ref="{urn:hl7-org:v3}effectiveTime"/>
 *         &lt;element ref="{urn:hl7-org:v3}component"/>
 *       &lt;/sequence>
 *       &lt;attribute name="moodCode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="EVN"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="classCode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="BATTERY"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "templateId", "id", "code", "statusCode", "effectiveTime", "component" })
@XmlRootElement(name = "organizer")
public class Organizer {

	@XmlElement(required = true)
	protected List<TemplateId> templateId;
	@XmlElement(required = true)
	protected Id id;
	@XmlElement(required = true)
	protected Code code;
	@XmlElement(required = true)
	protected StatusCode statusCode;
	@XmlElement(required = true)
	protected TEffectiveTime effectiveTime;
	@XmlElement(required = true)
	protected List<Component> component;
	@XmlAttribute(name = "moodCode", required = true)
	protected String moodCode;
	@XmlAttribute(name = "classCode", required = true)
	protected String classCode;

	/**
	 * Gets the value of the templateId property.
	 * 
	 * @return possible object is {@link TemplateId }
	 * 
	 */
	public List<TemplateId> getTemplateId() {
		return templateId;
	}

	/**
	 * Sets the value of the templateId property.
	 * 
	 * @param value
	 *            allowed object is {@link TemplateId }
	 * 
	 */
	public void setTemplateId(List<TemplateId> value) {
		this.templateId = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link Id }
	 * 
	 */
	public Id getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link Id }
	 * 
	 */
	public void setId(Id value) {
		this.id = value;
	}

	/**
	 * Gets the value of the code property.
	 * 
	 * @return possible object is {@link Code }
	 * 
	 */
	public Code getCode() {
		return code;
	}

	/**
	 * Sets the value of the code property.
	 * 
	 * @param value
	 *            allowed object is {@link Code }
	 * 
	 */
	public void setCode(Code value) {
		this.code = value;
	}

	/**
	 * Gets the value of the statusCode property.
	 * 
	 * @return possible object is {@link StatusCode }
	 * 
	 */
	public StatusCode getStatusCode() {
		return statusCode;
	}

	/**
	 * Sets the value of the statusCode property.
	 * 
	 * @param value
	 *            allowed object is {@link StatusCode }
	 * 
	 */
	public void setStatusCode(StatusCode value) {
		this.statusCode = value;
	}

	/**
	 * Gets the value of the effectiveTime property.
	 * 
	 * @return possible object is {@link TEffectiveTime }
	 * 
	 */
	public TEffectiveTime getEffectiveTime() {
		return effectiveTime;
	}

	/**
	 * Sets the value of the effectiveTime property.
	 * 
	 * @param value
	 *            allowed object is {@link TEffectiveTime }
	 * 
	 */
	public void setEffectiveTime(TEffectiveTime value) {
		this.effectiveTime = value;
	}

	public List<Component> getComponent() {
		if (component == null) {
			component = new ArrayList<Component>();
		}
		return component;
	}

	public void setComponent(List<Component> component) {
		this.component = component;
	}

	/**
	 * Gets the value of the moodCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMoodCode() {
		return moodCode;
	}

	/**
	 * Sets the value of the moodCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMoodCode(String value) {
		this.moodCode = value;
	}

	/**
	 * Gets the value of the classCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClassCode() {
		return classCode;
	}

	/**
	 * Sets the value of the classCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setClassCode(String value) {
		this.classCode = value;
	}

}
