//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element ref="{urn:hl7-org:v3}id"/>
 *           &lt;element ref="{urn:hl7-org:v3}code" minOccurs="0"/>
 *           &lt;element ref="{urn:hl7-org:v3}addr"/>
 *           &lt;element ref="{urn:hl7-org:v3}playingEntity"/>
 *         &lt;/sequence>
 *         &lt;element ref="{urn:hl7-org:v3}playingEntity"/>
 *       &lt;/choice>
 *       &lt;attribute name="classCode">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="MANU"/>
 *             &lt;enumeration value="PAT"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "content", "id", "playingEntity" })
@XmlRootElement(name = "participantRole")
public class ParticipantRole {

	/*
	 * @XmlElementRefs({
	 * 
	 * @XmlElementRef(name = "id", namespace = "urn:hl7-org:v3", type =
	 * Id.class),
	 * 
	 * @XmlElementRef(name = "addr", namespace = "urn:hl7-org:v3", type =
	 * Addr.class),
	 * 
	 * @XmlElementRef(name = "playingEntity", namespace = "urn:hl7-org:v3", type
	 * = PlayingEntity.class),
	 * 
	 * @XmlElementRef(name = "code", namespace = "urn:hl7-org:v3", type =
	 * Code.class) })
	 */
	protected List<Object> content;
	@XmlAttribute(name = "classCode")
	protected String classCode;
	@XmlElement(required = true)
	protected PlayingEntity playingEntity;
	@XmlElement(required = true)
	protected Id id;

	/**
	 * Gets the rest of the content model.
	 * 
	 * <p>
	 * You are getting this "catch-all" property because of the following
	 * reason: The field name "PlayingEntity" is used by two different parts of
	 * a schema. See: line 1286 of
	 * file:/C:/Users/Nitin/Workspace/Versaworks_Phase4
	 * /JAXB/phase2_xmlSchema.xsd line 1284 of
	 * file:/C:/Users/Nitin/Workspace/Versaworks_Phase4
	 * /JAXB/phase2_xmlSchema.xsd
	 * <p>
	 * To get rid of this property, apply a property customization to one of
	 * both of the following declarations to change their names: Gets the value
	 * of the content property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the content property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getContent().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Id }
	 * {@link PlayingEntity } {@link Addr } {@link Code }
	 * 
	 * 
	 */

	public Id getId() {
		return id;
	}

	public void setId(Id id) {
		this.id = id;
	}

	public List<Object> getContent() {
		if (content == null) {
			content = new ArrayList<Object>();
		}
		return this.content;
	}

	/**
	 * Gets the value of the classCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClassCode() {
		return classCode;
	}

	/**
	 * Sets the value of the classCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setClassCode(String value) {
		this.classCode = value;
	}

	public PlayingEntity getPlayingEntity() {
		return playingEntity;
	}

	public void setPlayingEntity(PlayingEntity playingEntity) {
		this.playingEntity = playingEntity;
	}

}
