//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}name"/>
 *         &lt;element ref="{urn:hl7-org:v3}administrativeGenderCode"/>
 *         &lt;element ref="{urn:hl7-org:v3}birthTime"/>
 *         &lt;element ref="{urn:hl7-org:v3}raceCode"/>
 *         &lt;element ref="{urn:hl7-org:v3}ethnicGroupCode"/>
 *         &lt;element ref="{urn:hl7-org:v3}languageCommunication"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "name", "administrativeGenderCode", "birthTime", "raceCode", "ethnicGroupCode",
		"languageCommunication" })
@XmlRootElement(name = "patient")
public class Patient {

	@XmlElement(required = true)
	protected Name name;
	@XmlElement(required = true)
	protected AdministrativeGenderCode administrativeGenderCode;
	@XmlElement(required = true)
	protected BirthTime birthTime;
	@XmlElement(required = true)
	protected RaceCode raceCode;
	@XmlElement(required = true)
	protected EthnicGroupCode ethnicGroupCode;
	@XmlElement(required = true)
	protected LanguageCommunication languageCommunication;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link Name }
	 * 
	 */
	public Name getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link Name }
	 * 
	 */
	public void setName(Name value) {
		this.name = value;
	}

	/**
	 * Gets the value of the administrativeGenderCode property.
	 * 
	 * @return possible object is {@link AdministrativeGenderCode }
	 * 
	 */
	public AdministrativeGenderCode getAdministrativeGenderCode() {
		return administrativeGenderCode;
	}

	/**
	 * Sets the value of the administrativeGenderCode property.
	 * 
	 * @param value
	 *            allowed object is {@link AdministrativeGenderCode }
	 * 
	 */
	public void setAdministrativeGenderCode(AdministrativeGenderCode value) {
		this.administrativeGenderCode = value;
	}

	/**
	 * Gets the value of the birthTime property.
	 * 
	 * @return possible object is {@link BirthTime }
	 * 
	 */
	public BirthTime getBirthTime() {
		return birthTime;
	}

	/**
	 * Sets the value of the birthTime property.
	 * 
	 * @param value
	 *            allowed object is {@link BirthTime }
	 * 
	 */
	public void setBirthTime(BirthTime value) {
		this.birthTime = value;
	}

	/**
	 * Gets the value of the raceCode property.
	 * 
	 * @return possible object is {@link RaceCode }
	 * 
	 */
	public RaceCode getRaceCode() {
		return raceCode;
	}

	/**
	 * Sets the value of the raceCode property.
	 * 
	 * @param value
	 *            allowed object is {@link RaceCode }
	 * 
	 */
	public void setRaceCode(RaceCode value) {
		this.raceCode = value;
	}

	/**
	 * Gets the value of the ethnicGroupCode property.
	 * 
	 * @return possible object is {@link EthnicGroupCode }
	 * 
	 */
	public EthnicGroupCode getEthnicGroupCode() {
		return ethnicGroupCode;
	}

	/**
	 * Sets the value of the ethnicGroupCode property.
	 * 
	 * @param value
	 *            allowed object is {@link EthnicGroupCode }
	 * 
	 */
	public void setEthnicGroupCode(EthnicGroupCode value) {
		this.ethnicGroupCode = value;
	}

	/**
	 * Gets the value of the languageCommunication property.
	 * 
	 * @return possible object is {@link LanguageCommunication }
	 * 
	 */
	public LanguageCommunication getLanguageCommunication() {
		return languageCommunication;
	}

	/**
	 * Sets the value of the languageCommunication property.
	 * 
	 * @param value
	 *            allowed object is {@link LanguageCommunication }
	 * 
	 */
	public void setLanguageCommunication(LanguageCommunication value) {
		this.languageCommunication = value;
	}

}
