//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{urn:hl7-org:v3}functionCode"/>
 *           &lt;element ref="{urn:hl7-org:v3}templateId"/>
 *         &lt;/choice>
 *         &lt;element ref="{urn:hl7-org:v3}assignedEntity"/>
 *       &lt;/sequence>
 *       &lt;attribute name="typeCode">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="PRF"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "functionCode", "templateId", "assignedEntity" })
@XmlRootElement(name = "performer")
public class Performer {

	protected FunctionCode functionCode;
	protected TemplateId templateId;
	@XmlElement(required = true)
	protected AssignedEntity assignedEntity;
	@XmlAttribute(name = "typeCode")
	protected String typeCode;

	/**
	 * Gets the value of the functionCode property.
	 * 
	 * @return possible object is {@link FunctionCode }
	 * 
	 */
	public FunctionCode getFunctionCode() {
		return functionCode;
	}

	/**
	 * Sets the value of the functionCode property.
	 * 
	 * @param value
	 *            allowed object is {@link FunctionCode }
	 * 
	 */
	public void setFunctionCode(FunctionCode value) {
		this.functionCode = value;
	}

	/**
	 * Gets the value of the templateId property.
	 * 
	 * @return possible object is {@link TemplateId }
	 * 
	 */
	public TemplateId getTemplateId() {
		return templateId;
	}

	/**
	 * Sets the value of the templateId property.
	 * 
	 * @param value
	 *            allowed object is {@link TemplateId }
	 * 
	 */
	public void setTemplateId(TemplateId value) {
		this.templateId = value;
	}

	/**
	 * Gets the value of the assignedEntity property.
	 * 
	 * @return possible object is {@link AssignedEntity }
	 * 
	 */
	public AssignedEntity getAssignedEntity() {
		return assignedEntity;
	}

	/**
	 * Sets the value of the assignedEntity property.
	 * 
	 * @param value
	 *            allowed object is {@link AssignedEntity }
	 * 
	 */
	public void setAssignedEntity(AssignedEntity value) {
		this.assignedEntity = value;
	}

	/**
	 * Gets the value of the typeCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTypeCode() {
		return typeCode;
	}

	/**
	 * Sets the value of the typeCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTypeCode(String value) {
		this.typeCode = value;
	}

}
