//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}manufacturedProduct"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "manufacturedProduct" })
@XmlRootElement(name = "product")
public class Product {

	@XmlElement(required = true)
	protected ManufacturedProduct manufacturedProduct;

	/**
	 * Gets the value of the manufacturedProduct property.
	 * 
	 * @return possible object is {@link ManufacturedProduct }
	 * 
	 */
	public ManufacturedProduct getManufacturedProduct() {
		return manufacturedProduct;
	}

	/**
	 * Sets the value of the manufacturedProduct property.
	 * 
	 * @param value
	 *            allowed object is {@link ManufacturedProduct }
	 * 
	 */
	public void setManufacturedProduct(ManufacturedProduct value) {
		this.manufacturedProduct = value;
	}

}
