//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}effectiveTime"/>
 *         &lt;element ref="{urn:hl7-org:v3}performer"/>
 *       &lt;/sequence>
 *       &lt;attribute name="moodCode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="EVN"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="classCode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="PCPR"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "effectiveTime", "performer" })
@XmlRootElement(name = "serviceEvent")
public class ServiceEvent {

	@XmlElement(required = true)
	protected TEffectiveTime effectiveTime;
	@XmlElement(required = true)
	protected List<Performer> performer;
	@XmlAttribute(name = "moodCode", required = true)
	protected String moodCode;
	@XmlAttribute(name = "classCode", required = true)
	protected String classCode;

	/**
	 * Gets the value of the effectiveTime property.
	 * 
	 * @return possible object is {@link TEffectiveTime }
	 * 
	 */
	public TEffectiveTime getEffectiveTime() {
		return effectiveTime;
	}

	/**
	 * Sets the value of the effectiveTime property.
	 * 
	 * @param value
	 *            allowed object is {@link TEffectiveTime }
	 * 
	 */
	public void setEffectiveTime(TEffectiveTime value) {
		this.effectiveTime = value;
	}

	/**
	 * Gets the value of the performer property.
	 * 
	 * @return possible object is {@link Performer }
	 * 
	 */

	/**
	 * Gets the value of the moodCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMoodCode() {
		return moodCode;
	}

	public List<Performer> getPerformer() {
		return performer;
	}

	public void setPerformer(List<Performer> performer) {
		this.performer = performer;
	}

	/**
	 * Sets the value of the moodCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMoodCode(String value) {
		this.moodCode = value;
	}

	/**
	 * Gets the value of the classCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClassCode() {
		return classCode;
	}

	/**
	 * Sets the value of the classCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setClassCode(String value) {
		this.classCode = value;
	}

}
