//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ST_given.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="ST_given">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="AIJAZ"/>
 *     &lt;enumeration value="CRAIG"/>
 *     &lt;enumeration value="Cpoe"/>
 *     &lt;enumeration value="M"/>
 *     &lt;enumeration value="PAUL"/>
 *     &lt;enumeration value="PORT"/>
 *     &lt;enumeration value="RIAZ"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ST_given")
@XmlEnum
public enum STGiven {

	A("A"), AIJAZ("AIJAZ"), CRAIG("CRAIG"), @XmlEnumValue("Cpoe")
	CPOE("Cpoe"), M("M"), PAUL("PAUL"), PORT("PORT"), RIAZ("RIAZ");
	private final String value;

	STGiven(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static STGiven fromValue(String v) {
		for (STGiven c : STGiven.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
