//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}templateId"/>
 *         &lt;element ref="{urn:hl7-org:v3}id"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{urn:hl7-org:v3}code"/>
 *             &lt;element ref="{urn:hl7-org:v3}statusCode"/>
 *             &lt;element ref="{urn:hl7-org:v3}effectiveTime"/>
 *             &lt;element ref="{urn:hl7-org:v3}consumable"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{urn:hl7-org:v3}text"/>
 *             &lt;element ref="{urn:hl7-org:v3}statusCode"/>
 *             &lt;element ref="{urn:hl7-org:v3}effectiveTime"/>
 *             &lt;element ref="{urn:hl7-org:v3}repeatNumber"/>
 *             &lt;element ref="{urn:hl7-org:v3}doseQuantity"/>
 *             &lt;element ref="{urn:hl7-org:v3}consumable"/>
 *             &lt;element ref="{urn:hl7-org:v3}performer"/>
 *             &lt;element ref="{urn:hl7-org:v3}entryRelationship" maxOccurs="unbounded"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="moodCode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="EVN"/>
 *             &lt;enumeration value="INT"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="classCode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="SBADM"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="negationInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "templateId", "id", "text", "statusCode", "effectiveTime", "routeCode",
		"doseQuantity", "consumable" })
@XmlRootElement(name = "substanceAdministration")
public class SubstanceAdministration {

	/*
	 * @XmlElementRefs({
	 * 
	 * @XmlElementRef(name = "effectiveTime", namespace = "urn:hl7-org:v3", type
	 * = JAXBElement.class),
	 * 
	 * @XmlElementRef(name = "id", namespace = "urn:hl7-org:v3", type =
	 * Id.class),
	 * 
	 * @XmlElementRef(name = "statusCode", namespace = "urn:hl7-org:v3", type =
	 * StatusCode.class),
	 * 
	 * @XmlElementRef(name = "entryRelationship", namespace = "urn:hl7-org:v3",
	 * type = EntryRelationship.class),
	 * 
	 * @XmlElementRef(name = "repeatNumber", namespace = "urn:hl7-org:v3", type
	 * = RepeatNumber.class),
	 * 
	 * @XmlElementRef(name = "consumable", namespace = "urn:hl7-org:v3", type =
	 * Consumable.class),
	 * 
	 * @XmlElementRef(name = "templateId", namespace = "urn:hl7-org:v3", type =
	 * TemplateId.class),
	 * 
	 * @XmlElementRef(name = "text", namespace = "urn:hl7-org:v3", type =
	 * Text.class),
	 * 
	 * @XmlElementRef(name = "performer", namespace = "urn:hl7-org:v3", type =
	 * Performer.class),
	 * 
	 * @XmlElementRef(name = "doseQuantity", namespace = "urn:hl7-org:v3", type
	 * = DoseQuantity.class),
	 * 
	 * @XmlElementRef(name = "code", namespace = "urn:hl7-org:v3", type =
	 * Code.class) })
	 */
	@XmlElement(required = true)
	protected List<TemplateId> templateId;
	@XmlElement(required = true)
	protected Id id;
	@XmlElement(required = true)
	protected String text;
	@XmlElement(required = true)
	protected StatusCode statusCode;
	@XmlElement(required = true)
	protected List<EffectiveTime> effectiveTime;
	@XmlElement(required = true)
	protected RouteCode routeCode;

	protected DoseQuantity doseQuantity;
	@XmlElement(required = true)
	protected Consumable consumable;

	@XmlAttribute(name = "moodCode", required = true)
	protected String moodCode;
	@XmlAttribute(name = "classCode", required = true)
	protected String classCode;
	@XmlAttribute(name = "negationInd")
	protected Boolean negationInd;

	/**
	 * Gets the rest of the content model.
	 * 
	 * <p>
	 * You are getting this "catch-all" property because of the following
	 * reason: The field name "StatusCode" is used by two different parts of a
	 * schema. See: line 1500 of
	 * file:/C:/Users/Nitin/Workspace/Versaworks_Phase4
	 * /JAXB/phase2_xmlSchema.xsd line 1494 of
	 * file:/C:/Users/Nitin/Workspace/Versaworks_Phase4
	 * /JAXB/phase2_xmlSchema.xsd
	 * <p>
	 * To get rid of this property, apply a property customization to one of
	 * both of the following declarations to change their names: Gets the value
	 * of the content property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the content property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getContent().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Id }
	 * {@link JAXBElement }{@code <}{@link TEffectiveTime }{@code >}
	 * {@link StatusCode } {@link EntryRelationship } {@link TemplateId }
	 * {@link Consumable } {@link RepeatNumber } {@link Text } {@link DoseQuantity }
	 * {@link Performer } {@link Code }
	 * 
	 * 
	 */

	/**
	 * Gets the value of the moodCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMoodCode() {
		return moodCode;
	}

	/**
	 * Sets the value of the moodCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMoodCode(String value) {
		this.moodCode = value;
	}

	/**
	 * Gets the value of the classCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClassCode() {
		return classCode;
	}

	/**
	 * Sets the value of the classCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setClassCode(String value) {
		this.classCode = value;
	}

	/**
	 * Gets the value of the negationInd property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isNegationInd() {
		return negationInd;
	}

	/**
	 * Sets the value of the negationInd property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setNegationInd(Boolean value) {
		this.negationInd = value;
	}

	public List<TemplateId> getTemplateId() {
		return templateId;
	}

	public void setTemplateId(List<TemplateId> templateId) {
		this.templateId = templateId;
	}

	public Id getId() {
		return id;
	}

	public void setId(Id id) {
		this.id = id;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public StatusCode getStatusCode() {
		return statusCode;
	}

	public void setStatusCode(StatusCode statusCode) {
		this.statusCode = statusCode;
	}

	public List<EffectiveTime> getEffectiveTime() {
		return effectiveTime;
	}

	public void setEffectiveTime(List<EffectiveTime> effectiveTime) {
		this.effectiveTime = effectiveTime;
	}

	public RouteCode getRouteCode() {
		return routeCode;
	}

	public void setRouteCode(RouteCode routeCode) {
		this.routeCode = routeCode;
	}

	public Consumable getConsumable() {
		return consumable;
	}

	public void setConsumable(Consumable consumable) {
		this.consumable = consumable;
	}

	public DoseQuantity getDoseQuantity() {
		return doseQuantity;
	}

	public void setDoseQuantity(DoseQuantity doseQuantity) {
		this.doseQuantity = doseQuantity;
	}

}
