//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}templateId"/>
 *         &lt;element ref="{urn:hl7-org:v3}id"/>
 *         &lt;element ref="{urn:hl7-org:v3}statusCode"/>
 *         &lt;element ref="{urn:hl7-org:v3}repeatNumber"/>
 *         &lt;element ref="{urn:hl7-org:v3}quantity" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}product"/>
 *         &lt;element ref="{urn:hl7-org:v3}author"/>
 *         &lt;element ref="{urn:hl7-org:v3}entryRelationship"/>
 *       &lt;/sequence>
 *       &lt;attribute name="moodCode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="INT"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="classCode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="SPLY"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "templateId", "id", "statusCode", "repeatNumber", "quantity", "product", "author",
		"entryRelationship" })
@XmlRootElement(name = "supply")
public class Supply {

	@XmlElement(required = true)
	protected TemplateId templateId;
	@XmlElement(required = true)
	protected Id id;
	@XmlElement(required = true)
	protected StatusCode statusCode;
	@XmlElement(required = true)
	protected RepeatNumber repeatNumber;
	protected Quantity quantity;
	@XmlElement(required = true)
	protected Product product;
	@XmlElement(required = true)
	protected Author author;
	@XmlElement(required = true)
	protected EntryRelationship entryRelationship;
	@XmlAttribute(name = "moodCode", required = true)
	protected String moodCode;
	@XmlAttribute(name = "classCode", required = true)
	protected String classCode;

	/**
	 * Gets the value of the templateId property.
	 * 
	 * @return possible object is {@link TemplateId }
	 * 
	 */
	public TemplateId getTemplateId() {
		return templateId;
	}

	/**
	 * Sets the value of the templateId property.
	 * 
	 * @param value
	 *            allowed object is {@link TemplateId }
	 * 
	 */
	public void setTemplateId(TemplateId value) {
		this.templateId = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link Id }
	 * 
	 */
	public Id getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link Id }
	 * 
	 */
	public void setId(Id value) {
		this.id = value;
	}

	/**
	 * Gets the value of the statusCode property.
	 * 
	 * @return possible object is {@link StatusCode }
	 * 
	 */
	public StatusCode getStatusCode() {
		return statusCode;
	}

	/**
	 * Sets the value of the statusCode property.
	 * 
	 * @param value
	 *            allowed object is {@link StatusCode }
	 * 
	 */
	public void setStatusCode(StatusCode value) {
		this.statusCode = value;
	}

	/**
	 * Gets the value of the repeatNumber property.
	 * 
	 * @return possible object is {@link RepeatNumber }
	 * 
	 */
	public RepeatNumber getRepeatNumber() {
		return repeatNumber;
	}

	/**
	 * Sets the value of the repeatNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link RepeatNumber }
	 * 
	 */
	public void setRepeatNumber(RepeatNumber value) {
		this.repeatNumber = value;
	}

	/**
	 * Gets the value of the quantity property.
	 * 
	 * @return possible object is {@link Quantity }
	 * 
	 */
	public Quantity getQuantity() {
		return quantity;
	}

	/**
	 * Sets the value of the quantity property.
	 * 
	 * @param value
	 *            allowed object is {@link Quantity }
	 * 
	 */
	public void setQuantity(Quantity value) {
		this.quantity = value;
	}

	/**
	 * Gets the value of the product property.
	 * 
	 * @return possible object is {@link Product }
	 * 
	 */
	public Product getProduct() {
		return product;
	}

	/**
	 * Sets the value of the product property.
	 * 
	 * @param value
	 *            allowed object is {@link Product }
	 * 
	 */
	public void setProduct(Product value) {
		this.product = value;
	}

	/**
	 * Gets the value of the author property.
	 * 
	 * @return possible object is {@link Author }
	 * 
	 */
	public Author getAuthor() {
		return author;
	}

	/**
	 * Sets the value of the author property.
	 * 
	 * @param value
	 *            allowed object is {@link Author }
	 * 
	 */
	public void setAuthor(Author value) {
		this.author = value;
	}

	/**
	 * Gets the value of the entryRelationship property.
	 * 
	 * @return possible object is {@link EntryRelationship }
	 * 
	 */
	public EntryRelationship getEntryRelationship() {
		return entryRelationship;
	}

	/**
	 * Sets the value of the entryRelationship property.
	 * 
	 * @param value
	 *            allowed object is {@link EntryRelationship }
	 * 
	 */
	public void setEntryRelationship(EntryRelationship value) {
		this.entryRelationship = value;
	}

	/**
	 * Gets the value of the moodCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMoodCode() {
		return moodCode;
	}

	/**
	 * Sets the value of the moodCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMoodCode(String value) {
		this.moodCode = value;
	}

	/**
	 * Gets the value of the classCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClassCode() {
		return classCode;
	}

	/**
	 * Sets the value of the classCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setClassCode(String value) {
		this.classCode = value;
	}

}
