//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}thead" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}tbody"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "thead", "tbody" })
@XmlRootElement(name = "table")
public class Table {

	protected Thead thead;
	@XmlElement(required = true)
	protected Tbody tbody;

	/**
	 * Gets the value of the thead property.
	 * 
	 * @return possible object is {@link Thead }
	 * 
	 */
	public Thead getThead() {
		return thead;
	}

	/**
	 * Sets the value of the thead property.
	 * 
	 * @param value
	 *            allowed object is {@link Thead }
	 * 
	 */
	public void setThead(Thead value) {
		this.thead = value;
	}

	/**
	 * Gets the value of the tbody property.
	 * 
	 * @return possible object is {@link Tbody }
	 * 
	 */
	public Tbody getTbody() {
		return tbody;
	}

	/**
	 * Sets the value of the tbody property.
	 * 
	 * @param value
	 *            allowed object is {@link Tbody }
	 * 
	 */
	public void setTbody(Tbody value) {
		this.tbody = value;
	}

}
