//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for T_effectiveTime complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="T_effectiveTime">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{urn:hl7-org:v3}low"/>
 *         &lt;element ref="{urn:hl7-org:v3}high" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="value">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="20140627"/>
 *             &lt;enumeration value="20140710224302-0700"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="nullFlavor">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="NI"/>
 *             &lt;enumeration value="UNK"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_effectiveTime", propOrder = { "low", "high" })
@XmlSeeAlso({ IVLTS.class })
public class TEffectiveTime {

	protected Low low;
	protected High high;
	@XmlAttribute(name = "value")
	protected String value;
	@XmlAttribute(name = "nullFlavor")
	protected String nullFlavor;

	/**
	 * Gets the value of the low property.
	 * 
	 * @return possible object is {@link Low }
	 * 
	 */
	public Low getLow() {
		return low;
	}

	/**
	 * Sets the value of the low property.
	 * 
	 * @param value
	 *            allowed object is {@link Low }
	 * 
	 */
	public void setLow(Low value) {
		this.low = value;
	}

	/**
	 * Gets the value of the high property.
	 * 
	 * @return possible object is {@link High }
	 * 
	 */
	public High getHigh() {
		return high;
	}

	/**
	 * Sets the value of the high property.
	 * 
	 * @param value
	 *            allowed object is {@link High }
	 * 
	 */
	public void setHigh(High value) {
		this.high = value;
	}

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the nullFlavor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNullFlavor() {
		return nullFlavor;
	}

	/**
	 * Sets the value of the nullFlavor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNullFlavor(String value) {
		this.nullFlavor = value;
	}

}
