//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="root" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="1.3.6.1.4.1.19376.1.5.3.1.4.5"/>
 *             &lt;enumeration value="2.16.840.1.1.113883.10.20.22.4.28"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.1.28"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.1.50"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.1.1"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.1"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.1.1"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.10"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.14"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.17"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.18"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.2"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.2.1"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.22"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.3"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.3.1"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.4"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.41"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.5"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.5.1"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.6"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.6.1"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.7"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.2.7.1"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.1"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.14"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.16"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.17"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.2"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.20"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.23"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.3"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.30"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.4"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.49"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.52"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.54"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.6"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.60"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.61"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.7"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.78"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.8"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.87"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.89"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.9"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.22.4.90"/>
 *             &lt;enumeration value="2.16.840.1.113883.10.20.6.2.1"/>
 *             &lt;enumeration value="2.16.840.1.113883.3.88.11.32.3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "templateId")
public class TemplateId {

	@XmlAttribute(name = "root", required = true)
	protected String root;

	/**
	 * Gets the value of the root property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRoot() {
		return root;
	}

	/**
	 * Sets the value of the root property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRoot(String value) {
		this.root = value;
	}

}
