//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 04:21:51 PM IST 
//

package com.versawork.http.ccd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for T_value complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="T_value">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}originalText" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="code">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;enumeration value="125668004"/>
 *             &lt;enumeration value="23406007"/>
 *             &lt;enumeration value="266919005"/>
 *             &lt;enumeration value="419199007"/>
 *             &lt;enumeration value="55561003"/>
 *             &lt;enumeration value="6736007"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="codeSystem">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="2.16.840.1.113883.6.96"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="nullFlavor">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="NA"/>
 *             &lt;enumeration value="NI"/>
 *             &lt;enumeration value="UNK"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="displayName">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Active"/>
 *             &lt;enumeration value="Allergy to Substance"/>
 *             &lt;enumeration value="Moderate"/>
 *             &lt;enumeration value="Never smoked tobacco (finding)"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="codeSystemName">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="SNOMED CT"/>
 *             &lt;enumeration value="SNOMED-CT"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T_value", propOrder = { "originalText" })
@XmlSeeAlso({ CE.class, PQ.class, CD.class })
public class TValue {

	protected OriginalText originalText;
	@XmlAttribute(name = "code")
	protected Integer code;
	@XmlAttribute(name = "codeSystem")
	protected String codeSystem;
	@XmlAttribute(name = "nullFlavor")
	protected String nullFlavor;
	@XmlAttribute(name = "displayName")
	protected String displayName;
	@XmlAttribute(name = "codeSystemName")
	protected String codeSystemName;

	/**
	 * Gets the value of the originalText property.
	 * 
	 * @return possible object is {@link OriginalText }
	 * 
	 */
	public OriginalText getOriginalText() {
		return originalText;
	}

	/**
	 * Sets the value of the originalText property.
	 * 
	 * @param value
	 *            allowed object is {@link OriginalText }
	 * 
	 */
	public void setOriginalText(OriginalText value) {
		this.originalText = value;
	}

	/**
	 * Gets the value of the code property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getCode() {
		return code;
	}

	/**
	 * Sets the value of the code property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setCode(Integer value) {
		this.code = value;
	}

	/**
	 * Gets the value of the codeSystem property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCodeSystem() {
		return codeSystem;
	}

	/**
	 * Sets the value of the codeSystem property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCodeSystem(String value) {
		this.codeSystem = value;
	}

	/**
	 * Gets the value of the nullFlavor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNullFlavor() {
		return nullFlavor;
	}

	/**
	 * Sets the value of the nullFlavor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNullFlavor(String value) {
		this.nullFlavor = value;
	}

	/**
	 * Gets the value of the displayName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDisplayName() {
		return displayName;
	}

	/**
	 * Sets the value of the displayName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDisplayName(String value) {
		this.displayName = value;
	}

	/**
	 * Gets the value of the codeSystemName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCodeSystemName() {
		return codeSystemName;
	}

	/**
	 * Sets the value of the codeSystemName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCodeSystemName(String value) {
		this.codeSystemName = value;
	}

}
